apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090      # grafana host 网络 → localhost 即本机 Prometheus
    isDefault: true
    editable: true
